server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    resolver 127.0.0.11 valid=30s;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass portfolio-laravel:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # 🔥 FIX DELAY
        fastcgi_connect_timeout 1s;
        fastcgi_send_timeout 3s;
        fastcgi_read_timeout 3s;

        # optional (boleh ada boleh nggak)
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~ /\.ht {
        deny all;
    }
}